name: Node.js CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: h5p-three-image
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: |
          cd h5p-three-image
          npm ci
          npm run build

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "8"
      - run: |
          mkdir -p dist
          cd dist

          while read -r repo; do git clone ${repo}; done < ../h5p-three-image/build_info/repos

          if [ -d "h5p-editor-audio-recorder" ]; then
            pushd h5p-editor-audio-recorder
            git checkout bec6fe1
            npm cache clean -f
            npm i webpack@2.7.0 webpack-sources@1.0.1 -g
            npm ci
            webpack
            popd
          fi

          rm -rf h5p-editor-three-image h5p-three-sixty

          git clone https://github.com/NDLANO/h5p-editor-three-image.git
          git clone https://github.com/NDLANO/h5p-editor-image-radio-group.git
          git clone https://github.com/NDLANO/h5p-three-sixty.git

          if [ -d "h5p-editor-three-image" ]; then pushd h5p-editor-three-image && npm ci && npm run build; popd; fi

          cp -r ../h5p-three-image .
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: |
          cd dist
          ls
          npm install -g h5p
          h5p pack -r h5p-three-image h5p-three-image.h5p
          h5p validate h5p-three-image.h5p
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: h5p-three-image.h5p
          path: dist/h5p-three-image.h5p
      - name: Load library.json
        id: set_library
        run: |
          ls
          JSON=$(cat ./h5p-three-image/library.json)
          JSON="${JSON//'%'/%25}"
          JSON="${JSON//$'\n'/%0A}"
          JSON="${JSON//$'\r'/%0D}"
          echo "::set-output name=library::${JSON}"
      - uses: "marvinpinto/action-automatic-releases@latest" # https://github.com/marvinpinto/actions/tree/master/packages/automatic-releases
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: |
            ${{ 
              format(
                'v{0}.{1}.{2}',
                fromJson(steps.set_library.outputs.library).majorVersion,
                fromJson(steps.set_library.outputs.library).minorVersion,
                fromJson(steps.set_library.outputs.library).patchVersion
              )
            }}
          prerelease: false
          files: |
            dist/h5p-three-image.h5p